package Interface.PPaciente;

import java.sql.SQLException;
import jdbc.JdbcOrina;

public class Orina extends javax.swing.JPanel {

    SeleccionPacientes sp = null;

    public Orina(SeleccionPacientes p) throws SQLException {
        this.sp = p;
        initComponents();
        JdbcOrina jo = new JdbcOrina();
        domain.Orina or = jo.select(p.paciente.getIdPaciente());
        if (or != null) {
            textGlucosa.setText("" + or.getGlucosa());
            textDensidad.setText("" + or.getDensidad());
            textPh.setText("" + or.getpH());
            textSodio.setText("" + or.getSodio());
            botonAgregarMuestra.setVisible(false);
        } else {
            botonModificarMuestra.setVisible(false);
            botonEliminarMuestra.setVisible(false);
        }

        if (or != null) {

            textGlucosaExamen.setText(validar(or.getGlucosa(), 0, 0.8));

            textDensidadExamen.setText(validar(or.getDensidad(), 1000, 1030));

            textPhExamen.setText(validar(or.getpH(), 4, 8));

            textSodioExamen.setText(validar(or.getSodio(), 40, 220));

        } else {
            textGlucosaExamen.setText("No ha ingresado datos");
            textDensidadExamen.setText("No ha ingresado datos");
            textPhExamen.setText("No ha ingresado datos");
            textSodioExamen.setText("No ha ingresado datos");
        }
    }

    private String validar(double comparador, double min, double max) {
        if (comparador < min) {
            return "Niveles bajos";
        } else if (comparador >= min && comparador <= max) {
            return "Niveles normales";
        } else {
            return "Niveles altos";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Glucosa = new javax.swing.JLabel();
        Densidad = new javax.swing.JLabel();
        pH = new javax.swing.JLabel();
        Sodio = new javax.swing.JLabel();
        textGlucosa = new javax.swing.JLabel();
        textDensidad = new javax.swing.JLabel();
        textSodio = new javax.swing.JLabel();
        textPh = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botonAgregarMuestra = new javax.swing.JButton();
        botonModificarMuestra = new javax.swing.JButton();
        botonEliminarMuestra = new javax.swing.JButton();
        TituloRangos = new javax.swing.JLabel();
        RangoGlucosa = new javax.swing.JLabel();
        RangoDensidad = new javax.swing.JLabel();
        RangopH = new javax.swing.JLabel();
        RangoSodio = new javax.swing.JLabel();
        textGlucosaExamen = new javax.swing.JLabel();
        textDensidadExamen = new javax.swing.JLabel();
        textPhExamen = new javax.swing.JLabel();
        textSodioExamen = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(773, 327));

        Glucosa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Glucosa.setForeground(new java.awt.Color(0, 0, 0));
        Glucosa.setText("Glucosa:");

        Densidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Densidad.setForeground(new java.awt.Color(0, 0, 0));
        Densidad.setText("Densidad:");

        pH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pH.setForeground(new java.awt.Color(0, 0, 0));
        pH.setText("pH: ");

        Sodio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Sodio.setForeground(new java.awt.Color(0, 0, 0));
        Sodio.setText("Sodio:");

        textGlucosa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        textDensidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        textSodio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        textPh.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("RANGOS OBTENIDOS");

        botonAgregarMuestra.setText("Agregar Muestra");
        botonAgregarMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarMuestraActionPerformed(evt);
            }
        });

        botonModificarMuestra.setText("Modificar Muestra");
        botonModificarMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarMuestraActionPerformed(evt);
            }
        });

        botonEliminarMuestra.setText("Eliminar Muestra");
        botonEliminarMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarMuestraActionPerformed(evt);
            }
        });

        TituloRangos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TituloRangos.setForeground(new java.awt.Color(0, 0, 0));
        TituloRangos.setText("RANGOS NORMALES");

        RangoGlucosa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RangoGlucosa.setForeground(new java.awt.Color(0, 0, 0));
        RangoGlucosa.setText("0 a 0.8 mmol/l");

        RangoDensidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RangoDensidad.setForeground(new java.awt.Color(0, 0, 0));
        RangoDensidad.setText("1000-1030 g/mL");

        RangopH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RangopH.setForeground(new java.awt.Color(0, 0, 0));
        RangopH.setText("4 - 8");

        RangoSodio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RangoSodio.setForeground(new java.awt.Color(0, 0, 0));
        RangoSodio.setText("40-220 mEq/L");

        textGlucosaExamen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        textDensidadExamen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        textPhExamen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        textSodioExamen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgregarMuestra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonModificarMuestra))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sodio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textSodio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pH, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Glucosa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Densidad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textGlucosa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(textPh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(botonEliminarMuestra)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RangoGlucosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RangoDensidad, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(RangopH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RangoSodio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(TituloRangos, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textGlucosaExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(textDensidadExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPhExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textSodioExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TituloRangos, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textGlucosa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RangoGlucosa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Glucosa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textGlucosaExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDensidadExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(textPhExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(textSodioExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RangoDensidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(RangopH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(RangoSodio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Densidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textPh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Sodio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textSodio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonModificarMuestra)
                                    .addComponent(botonEliminarMuestra))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonAgregarMuestra)
                                .addGap(18, 18, 18))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarMuestraActionPerformed
        try {
            DialogPaciente panel = new DialogPaciente(new javax.swing.JFrame(), true, 5, sp.paciente);
            panel.setLocationRelativeTo(this);
            panel.setVisible(true);
            Orina pipi = new Orina(sp);
            sp.cargarPanel(pipi);
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_botonAgregarMuestraActionPerformed

    private void botonModificarMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarMuestraActionPerformed
        try {
            DialogPaciente panel = new DialogPaciente(new javax.swing.JFrame(), true, 8, sp.paciente);
            panel.setLocationRelativeTo(this);
            panel.setVisible(true);
            Orina pipi = new Orina(sp);
            sp.cargarPanel(pipi);
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_botonModificarMuestraActionPerformed

    private void botonEliminarMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarMuestraActionPerformed
        try {
            domain.Orina orina = new JdbcOrina().select(sp.paciente.getIdPaciente());
            new JdbcOrina().delete(orina);
            Orina pipi = new Orina(sp);
            sp.cargarPanel(pipi);
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_botonEliminarMuestraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Densidad;
    private javax.swing.JLabel Glucosa;
    private javax.swing.JLabel RangoDensidad;
    private javax.swing.JLabel RangoGlucosa;
    private javax.swing.JLabel RangoSodio;
    private javax.swing.JLabel RangopH;
    private javax.swing.JLabel Sodio;
    private javax.swing.JLabel TituloRangos;
    private javax.swing.JButton botonAgregarMuestra;
    private javax.swing.JButton botonEliminarMuestra;
    private javax.swing.JButton botonModificarMuestra;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel pH;
    private javax.swing.JLabel textDensidad;
    private javax.swing.JLabel textDensidadExamen;
    private javax.swing.JLabel textGlucosa;
    private javax.swing.JLabel textGlucosaExamen;
    private javax.swing.JLabel textPh;
    private javax.swing.JLabel textPhExamen;
    private javax.swing.JLabel textSodio;
    private javax.swing.JLabel textSodioExamen;
    // End of variables declaration//GEN-END:variables
}
